package com.example

import com.lagradost.cloudstream3.*
import com.lagradost.cloudstream3.utils.ExtractorLink
import com.lagradost.cloudstream3.utils.fixUrl
import com.lagradost.cloudstream3.utils.fixUrlNull
import com.lagradost.cloudstream3.utils.loadExtractor
import com.lagradost.cloudstream3.LoadResponse.Companion.addTrailer

class ExampleProvider : MainAPI() {
    override var mainUrl = "https://movy.sx"
        override var name = "Movy"
            override val hasMainPage = true
                override var lang = "en"
                    override val hasQuickSearch = false
                        override val supportedTypes = setOf(TvType.Movie, TvType.TvSeries)

                            // 1. Ana Sayfa
                                override suspend fun getMainPage(page: Int, request: MainPageRequest): HomePageResponse {
                                        val document = app.get(mainUrl).document
                                                val home = document.select("div.flw-item").mapNotNull {
                                                            val title = it.selectFirst("h2.film-name")?.text() ?: return@mapNotNull null
                                                                        val href = fixUrl(it.selectFirst("a")?.attr("href") ?: return@mapNotNull null)
                                                                                    val poster = fixUrlNull(it.selectFirst("img")?.attr("data-src"))

                                                                                                newMovieSearchResponse(title, href, TvType.Movie) {
                                                                                                                this.posterUrl = poster
                                                                                                                            }
                                                                                                                                    }
                                                                                                                                            return newHomePageResponse(listOf(HomePageList("Latest", home)))
                                                                                                                                                }

                                                                                                                                                    // 2. Arama
                                                                                                                                                        override suspend fun search(query: String): List<SearchResponse> {
                                                                                                                                                                val url = "$mainUrl/search/$query"
                                                                                                                                                                        val document = app.get(url).document

                                                                                                                                                                                return document.select("div.flw-item").mapNotNull {
                                                                                                                                                                                            val title = it.selectFirst("h2.film-name")?.text() ?: return@mapNotNull null
                                                                                                                                                                                                        val href = fixUrl(it.selectFirst("a")?.attr("href") ?: return@mapNotNull null)
                                                                                                                                                                                                                    val poster = fixUrlNull(it.selectFirst("img")?.attr("data-src"))

                                                                                                                                                                                                                                newMovieSearchResponse(title, href, TvType.Movie) {
                                                                                                                                                                                                                                                this.posterUrl = poster
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                            // 3. Detay Sayfası
                                                                                                                                                                                                                                                                                override suspend fun load(url: String): LoadResponse {
                                                                                                                                                                                                                                                                                        val document = app.get(url).document
                                                                                                                                                                                                                                                                                                val title = document.selectFirst("h2.heading-name")?.text() ?: ""
                                                                                                                                                                                                                                                                                                        val poster = fixUrlNull(document.selectFirst("div.miv-cover img")?.attr("src"))
                                                                                                                                                                                                                                                                                                                val description = document.selectFirst("div.description")?.text()

                                                                                                                                                                                                                                                                                                                        return newMovieLoadResponse(title, url, TvType.Movie, url) {
                                                                                                                                                                                                                                                                                                                                    this.posterUrl = poster
                                                                                                                                                                                                                                                                                                                                                this.plot = description
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                // 4. Video Oynatıcı Linklerini Çekme
                                                                                                                                                                                                                                                                                                                                                                    override suspend fun loadLinks(
                                                                                                                                                                                                                                                                                                                                                                            data: String,
                                                                                                                                                                                                                                                                                                                                                                                    isCasting: Boolean,
                                                                                                                                                                                                                                                                                                                                                                                            subtitleCallback: (SubtitleFile) -> Unit,
                                                                                                                                                                                                                                                                                                                                                                                                    callback: (ExtractorLink) -> Unit
                                                                                                                                                                                                                                                                                                                                                                                                        ): Boolean {
                                                                                                                                                                                                                                                                                                                                                                                                                val document = app.get(data).document

                                                                                                                                                                                                                                                                                                                                                                                                                        val iframes = document.select("iframe").mapNotNull { it.attr("src") }
                                                                                                                                                                                                                                                                                                                                                                                                                                for (iframe in iframes) {
                                                                                                                                                                                                                                                                                                                                                                                                                                            val fullUrl = fixUrl(iframe)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        loadExtractor(fullUrl, subtitleCallback, callback)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return true
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            