package com.example

import com.lagradost.cloudstream3.*
import com.lagradost.cloudstream3.utils.ExtractorLink

class ExampleProvider : MainAPI() {
    override var mainUrl = "https://movy.sx"
        override var name = "Movy"
            override val hasMainPage = true
                override var lang = "en"
                    override val hasQuickSearch = false
                        override val supportedTypes = setOf(TvType.Movie, TvType.TvSeries)

                            private fun fixUrl(url: String): String {
                                    return when {
                                                url.startsWith("http://") || url.startsWith("https://") -> url
                                                            url.startsWith("//") -> "https:$url"
                                                                        url.startsWith("/") -> "$mainUrl$url"
                                                                                    else -> "$mainUrl/$url"
                                                                                            }
                                                                                                }

                                                                                                    override suspend fun getMainPage(page: Int, request: MainPageRequest): HomePageResponse {
                                                                                                            val document = app.get(mainUrl).document
                                                                                                                    val home = document.select("div.flw-item").mapNotNull {
                                                                                                                                val title = it.selectFirst("h2.film-name")?.text() ?: return@mapNotNull null
                                                                                                                                            val rawHref = it.selectFirst("a")?.attr("href") ?: return@mapNotNull null
                                                                                                                                                        val poster = it.selectFirst("img")?.attr("data-src")?.let { src -> fixUrl(src) }

                                                                                                                                                                    newMovieSearchResponse(title, fixUrl(rawHref), TvType.Movie) {
                                                                                                                                                                                    this.posterUrl = poster
                                                                                                                                                                                                }
                                                                                                                                                                                                        }
                                                                                                                                                                                                                return newHomePageResponse(listOf(HomePageList("Latest", home)))
                                                                                                                                                                                                                    }

                                                                                                                                                                                                                        override suspend fun search(query: String): List<SearchResponse> {
                                                                                                                                                                                                                                val url = "$mainUrl/search/$query"
                                                                                                                                                                                                                                        val document = app.get(url).document

                                                                                                                                                                                                                                                return document.select("div.flw-item").mapNotNull {
                                                                                                                                                                                                                                                            val title = it.selectFirst("h2.film-name")?.text() ?: return@mapNotNull null
                                                                                                                                                                                                                                                                        val rawHref = it.selectFirst("a")?.attr("href") ?: return@mapNotNull null
                                                                                                                                                                                                                                                                                    val poster = it.selectFirst("img")?.attr("data-src")?.let { src -> fixUrl(src) }

                                                                                                                                                                                                                                                                                                newMovieSearchResponse(title, fixUrl(rawHref), TvType.Movie) {
                                                                                                                                                                                                                                                                                                                this.posterUrl = poster
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                            override suspend fun load(url: String): LoadResponse {
                                                                                                                                                                                                                                                                                                                                                    val document = app.get(url).document
                                                                                                                                                                                                                                                                                                                                                            val title = document.selectFirst("h2.heading-name")?.text() ?: ""
                                                                                                                                                                                                                                                                                                                                                                    val poster = document.selectFirst("div.miv-cover img")?.attr("src")?.let { fixUrl(it) }
                                                                                                                                                                                                                                                                                                                                                                            val description = document.selectFirst("div.description")?.text()

                                                                                                                                                                                                                                                                                                                                                                                    return newMovieLoadResponse(title, url, TvType.Movie, url) {
                                                                                                                                                                                                                                                                                                                                                                                                this.posterUrl = poster
                                                                                                                                                                                                                                                                                                                                                                                                            this.plot = description
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                            override suspend fun loadLinks(
                                                                                                                                                                                                                                                                                                                                                                                                                                    data: String,
                                                                                                                                                                                                                                                                                                                                                                                                                                            isCasting: Boolean,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    subtitleCallback: (SubtitleFile) -> Unit,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            callback: (ExtractorLink) -> Unit
                                                                                                                                                                                                                                                                                                                                                                                                                                                                ): Boolean {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        val document = app.get(data).document
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                val iframes = document.select("iframe").mapNotNull { it.attr("src") }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (iframe in iframes) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    val fullUrl = fixUrl(iframe)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                callback.invoke(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ExtractorLink(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    source = name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        name = name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            url = fullUrl,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                referer = "$mainUrl/",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    quality = 0, // 0 = Qualities.Unknown
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        isM3u8 = fullUrl.contains(".m3u8")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return true
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        